version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running Django checks..."
      - python manage.py check || true

  build:
    commands:
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput || true
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
